# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR16e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69187/99473_UR16e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    min_position: !degrees -360.0
    max_position: !degrees  360.0
    has_velocity_limits: true
    max_velocity: !degrees  120.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 330.0
  shoulder_lift_joint:
    has_position_limits: true
    min_position: !degrees -360.0
    max_position: !degrees  360.0
    has_velocity_limits: true
    max_velocity: !degrees  120.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 330.0
  elbow_joint:
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    has_position_limits: true
    min_position: !degrees -180.0
    max_position: !degrees  180.0
    has_velocity_limits: true
    max_velocity: !degrees  180.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_1_joint:
    has_position_limits: true
    min_position: !degrees -360.0
    max_position: !degrees  360.0
    has_velocity_limits: true
    max_velocity: !degrees  180.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0
  wrist_2_joint:
    has_position_limits: true
    min_position: !degrees -360.0
    max_position: !degrees  360.0
    has_velocity_limits: true
    max_velocity: !degrees  180.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0
  wrist_3_joint:
    has_position_limits: true
    min_position: !degrees -360.0
    max_position: !degrees  360.0
    has_velocity_limits: true
    max_velocity: !degrees  180.0
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0
