# Physical parameters

offsets:
  shoulder_offset: 0.176 # measured from model
  elbow_offset: 0.040 # measured from model

inertia_parameters:
  # taken from https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/
  base_mass: 4.0  # This mass might be incorrect
  shoulder_mass: 7.369
  upper_arm_mass: 10.450
  forearm_mass: 4.321
  wrist_1_mass: 2.180
  wrist_2_mass: 2.033
  wrist_3_mass: 0.907

  shoulder_radius: x0.060   # FROM UR5 CURRENTLY NOT USED ANYMORE
  upper_arm_radius: x0.054  # FROM UR5 CURRENTLY NOT USED ANYMORE
  elbow_radius: x0.060      # FROM UR5 CURRENTLY NOT USED ANYMORE
  forearm_radius: x0.040    # FROM UR5 CURRENTLY NOT USED ANYMORE
  wrist_radius: x0.045      # FROM UR5 CURRENTLY NOT USED ANYMORE

  links:
    base:
      radius: 0.075
      length: 0.038

  # model referring to https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/
  center_of_mass:
    shoulder_cog:
      x: 0.0        # model.x
      y: -0.030     # -model.z
      z: -0.016     # model.y
    upper_arm_cog:
      x: -0.1764    # model.x - upperarm_length
      y: 0.0        # model.y
      z: 0.16       # model.z
    forearm_cog:
      x: -0.166     # model.x - forearm_length
      y: 0.0        # model.y
      z: 0.065      # model.z
    wrist_1_cog:
      x: 0.0        # model.x
      y: -0.011     # -model.z
      z: -0.009     # model.y
    wrist_2_cog:
      x: 0.0        # model.x
      y: 0.012      # model.z
      z: -0.018     # -model.y
    wrist_3_cog:
      x: 0.0        # model.x
      y: 0.0        # model.y
      z: -0.044     # model.z

  rotation:
    shoulder:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    upper_arm:
      roll: 0
      pitch: 0
      yaw: 0
    forearm:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_1:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    wrist_2:
      roll: -1.570796326794897
      pitch: 0
      yaw: 0
    wrist_3:
      roll: 0
      pitch: 0
      yaw: 0

  tensor:
    shoulder:
      ixx: 0.03351
      ixy: 0.00002
      ixz: -0.00001
      iyy: 0.03374
      iyz: 0.00374
      izz: 0.02100
    upper_arm:
      ixx: 0.02796
      ixy: -0.00010
      ixz: -0.00720
      iyy: 0.47558
      iyz: 0.00003
      izz: 0.47635
    forearm:
      ixx: 0.01091
      ixy: 0.00006
      ixz: 0.01012
      iyy: 0.12060
      iyz: 0.00001
      izz: 0.11714
    wrist_1:
      ixx: 0.00609
      ixy: -0.00001
      ixz: 0.0
      iyy: 0.00245
      iyz: 0.00083
      izz: 0.00579
    wrist_2:
      ixx: 0.00389
      ixy: -0.00001
      ixz: 0.0
      iyy: 0.00219
      iyz: -0.00045
      izz: 0.00363
    wrist_3:
      ixx: 0.00117
      ixy: 0.0
      ixz: 0.0
      iyy: 0.00118
      iyz: 0.0
      izz: 0.00084
